### ISSUE TITLE
TypeError: forward() missing 3 required positional arguments: 'x_mark_enc', 'x_dec', and 'x_mark_dec'

### ISSUE THREAD

**Issue by sblk07** [syrGitHub/TFPS#1]
Trying to train model with default ETT dataset with default params, I get this issue.
Probably a mismatch with torch version? Would be nice if you can supply requirements.txt and have a look at this issue.

Happens exactly when this is called:
self._get_profile(self.model)

Thanks.

**Comment by syrGitHub** [comment]
I have updated the requirements.txt and the scripts, you can try it again.
And you need to set the model_name=PatchTST_MoE_cluster.
